require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNFirebase' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # add the Firebase pod for Google Analytics
  pod 'Firebase/CoreOnly'
  # pod 'FirebaseCoreDiagnostics', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :branch=>'release-6.33.0'
  # pod 'GoogleDataTransport', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :branch=>'release-6.33.0'

  target 'RNFirebaseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNFirebase-tvOS' do
  # Pods for RNFirebase-tvOS

  target 'RNFirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
